category_icon_list:
  default: "help,question-circle,#CC0000,partial|"
  type: "list"
  list_type: "simple"
  description: '  Enter comma-delimited configuration for categories<br><br>Format: "slug,icon,color,partial"<br><br>slug â€” The category slug.<br><br>icon â€” Can be either (1) a Font Awesome icon, (2) a singular unicode character "ðŸ˜€", or (3) a forum emoji formatted like ":grinning:"<br><br>color (optional) â€” Color for the icon. Use a hex code with the "#" character. Default color is the category color.<br><br>partial (optional) â€” A color must be set first to activate this. Write "partial" if the slug only needs to partially match the category-slug, otherwise an exact match is required. Useful for subcategories with identical names.'
svg_icons:
  default: "question-circle"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component"
category_lock_icon:
  default: ""
  description: "Enter the name of a FontAwesome 5 icon to display instead of the lock icon next to private categories."
use_category_logo:
  type: bool
  default: false
  description: "Use the category's uploaded logo as its icon.<br><br><strong>Overrides</strong> Font Awesome icons and emojis.<br><br>Category logos can be uploaded through individual category settings."