category_icon_list:
  default: "help,question-circle,#CC0000,partial|"
  type: "list"
  list_type: "simple"
  description: 'Enter comma-delimited configuration for categories, in the format "slug,icon,color,match". Color can be in hex format (#123456) or left blank, then the default color for the category is used (same as the Badge color). If  match is "partial" then the slug need only partially match the category-slug, otherwise an exact match is required'
render_category_icon_in_post:
  default: true
  description: "Show category icons in the post body"
svg_icons:
  default: "question-circle"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component"
category_lock_icon:
  default: ""
  description: "Enter the name of a FontAwesome 5 icon to display instead of the lock icon next to private categories."
