category_icon_list: 
  default: 'help,question-circle,#CC0000,partial|'
  type: 'list'
  description: 'Enter comma-delimited configuration for categories, in the format "slug,icon,colour,match". Colour in format #123456 or "catcol" to use the default colour for the category (same as the Badge colour). If  match is "partial" then the slug need only partially match the category-slug, otherwise an exact match is required'
svg_icons: 
  default: 'question-circle'
  type: 'list'
  list_type: 'compact'
  description: 'List of FontAwesome 5 icons used in this theme component'
category_lock_icon: 
  default: ''
  description: 'Enter the name of a FontAwesome 5 icon to display instead of the lock icon next to private categories.'